# Generated by Django 4.2.22 on 2026-02-03 10:00

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.iam


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_auto_20260105_1406'),
    ]

    operations = [
        # Create IAM Group
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Group Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_groups', to='db.workspace')),
            ],
            options={
                'verbose_name': 'IAM Group',
                'verbose_name_plural': 'IAM Groups',
                'db_table': 'iam_groups',
                'ordering': ('-created_at',),
            },
        ),
        # Create IAM Policy
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Policy Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Policy Description')),
                ('document', models.JSONField(default=plane.db.models.iam.get_default_policy_document, help_text='JSON policy document with version and statements', verbose_name='Policy Document')),
                ('is_managed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_policies', to='db.workspace')),
            ],
            options={
                'verbose_name': 'IAM Policy',
                'verbose_name_plural': 'IAM Policies',
                'db_table': 'iam_policies',
                'ordering': ('-created_at',),
            },
        ),
        # Create Project Group (visual grouping)
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Project Group Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Group Description')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_groups', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Project Group',
                'verbose_name_plural': 'Project Groups',
                'db_table': 'project_groups',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        # Create Group Member
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='db.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_group_members', to='db.workspace')),
            ],
            options={
                'verbose_name': 'IAM Group Member',
                'verbose_name_plural': 'IAM Group Members',
                'db_table': 'iam_group_members',
                'ordering': ('-created_at',),
            },
        ),
        # Create Group Policy
        migrations.CreateModel(
            name='GroupPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='db.group')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_attachments', to='db.policy')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_group_policies', to='db.workspace')),
            ],
            options={
                'verbose_name': 'IAM Group Policy',
                'verbose_name_plural': 'IAM Group Policies',
                'db_table': 'iam_group_policies',
                'ordering': ('-created_at',),
            },
        ),
        # Create User Policy
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_user_policies', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attachments', to='db.policy')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iam_user_policies', to='db.workspace')),
            ],
            options={
                'verbose_name': 'IAM User Policy',
                'verbose_name_plural': 'IAM User Policies',
                'db_table': 'iam_user_policies',
                'ordering': ('-created_at',),
            },
        ),
        # Add project_group FK to Project
        migrations.AddField(
            model_name='project',
            name='project_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='db.projectgroup'),
        ),
        # Unique constraints for Group
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'workspace'), name='iam_group_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'workspace', 'deleted_at')},
        ),
        # Unique constraints for Policy
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'workspace'), name='iam_policy_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together={('name', 'workspace', 'deleted_at')},
        ),
        # Unique constraints for ProjectGroup
        migrations.AddConstraint(
            model_name='projectgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'workspace'), name='project_group_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='projectgroup',
            unique_together={('name', 'workspace', 'deleted_at')},
        ),
        # Unique constraints for GroupMember
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('group', 'member'), name='iam_group_member_unique_group_member_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'member', 'deleted_at')},
        ),
        # Unique constraints for GroupPolicy
        migrations.AddConstraint(
            model_name='grouppolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('group', 'policy'), name='iam_group_policy_unique_group_policy_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='grouppolicy',
            unique_together={('group', 'policy', 'deleted_at')},
        ),
        # Unique constraints for UserPolicy
        migrations.AddConstraint(
            model_name='userpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'policy', 'workspace'), name='iam_user_policy_unique_user_policy_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='userpolicy',
            unique_together={('user', 'policy', 'workspace', 'deleted_at')},
        ),
    ]
